// AUTO-GENERATED by scripts/build-icons.ts. Do not edit.
import Icon_a2i from './a2i.png';
import Icon_aidevops from './aidevops.png';
import Icon_amazonq from './amazonq.png';
import Icon_apigateway from './apigateway.png';
import Icon_appstream2 from './appstream2.png';
import Icon_appstudio from './appstudio.png';
import Icon_appsync from './appsync.png';
import Icon_athena from './athena.png';
import Icon_bedrock from './bedrock.png';
import Icon_bedrockagentcore from './bedrockagentcore.png';
import Icon_billing from './billing.png';
import Icon_biodiscovery from './biodiscovery.png';
import Icon_cloudformation from './cloudformation.png';
import Icon_cloudfront from './cloudfront.png';
import Icon_cloudtrail from './cloudtrail.png';
import Icon_cloudwatch from './cloudwatch.png';
import Icon_composer from './composer.png';
import Icon_config from './config.png';
import Icon_connecthealth from './connecthealth.png';
import Icon_console from './console.png';
import Icon_costexplorer from './costexplorer.png';
import Icon_costmanagement from './costmanagement.png';
import Icon_datatransferterminal from './datatransferterminal.png';
import Icon_deadlinecloud from './deadlinecloud.png';
import Icon_dynamodb from './dynamodb.png';
import Icon_ec2 from './ec2.png';
import Icon_ec2globalview from './ec2globalview.png';
import Icon_ecr from './ecr.png';
import Icon_ecs from './ecs.png';
import Icon_eks from './eks.png';
import Icon_elementalinference from './elementalinference.png';
import Icon_endusermessaging from './endusermessaging.png';
import Icon_eventbridge from './eventbridge.png';
import Icon_evs from './evs.png';
import Icon_firehose from './firehose.png';
import Icon_fis from './fis.png';
import Icon_flink from './flink.png';
import Icon_forsap from './forsap.png';
import Icon_gameliftservers from './gameliftservers.png';
import Icon_gameliftstreams from './gameliftstreams.png';
import Icon_glacier from './glacier.png';
import Icon_globalview from './globalview.png';
import Icon_glue from './glue.png';
import Icon_grafana from './grafana.png';
import Icon_iam from './iam.png';
import Icon_kms from './kms.png';
import Icon_lambda from './lambda.png';
import Icon_mediaconnect from './mediaconnect.png';
import Icon_mediaconvert from './mediaconvert.png';
import Icon_medialive from './medialive.png';
import Icon_mediapackage from './mediapackage.png';
import Icon_mediastore from './mediastore.png';
import Icon_mediatailor from './mediatailor.png';
import Icon_memorydb from './memorydb.png';
import Icon_msk from './msk.png';
import Icon_mwaa from './mwaa.png';
import Icon_notifications from './notifications.png';
import Icon_novaact from './novaact.png';
import Icon_odb from './odb.png';
import Icon_opensearch from './opensearch.png';
import Icon_organizations from './organizations.png';
import Icon_outposts from './outposts.png';
import Icon_partnercentral from './partnercentral.png';
import Icon_pcs from './pcs.png';
import Icon_prometheus from './prometheus.png';
import Icon_rbin from './rbin.png';
import Icon_rds from './rds.png';
import Icon_resourcegroups from './resourcegroups.png';
import Icon_route53 from './route53.png';
import Icon_route53globalresolver from './route53globalresolver.png';
import Icon_route53recovery from './route53recovery.png';
import Icon_rtbfabric from './rtbfabric.png';
import Icon_s3 from './s3.png';
import Icon_sagemaker from './sagemaker.png';
import Icon_scn from './scn.png';
import Icon_secretsmanager from './secretsmanager.png';
import Icon_securityagent from './securityagent.png';
import Icon_securityir from './securityir.png';
import Icon_servicequotas from './servicequotas.png';
import Icon_ses from './ses.png';
import Icon_snowfamily from './snowfamily.png';
import Icon_sns from './sns.png';
import Icon_sqs from './sqs.png';
import Icon_sso from './sso.png';
import Icon_stepfunctions from './stepfunctions.png';
import Icon_sustainability from './sustainability.png';
import Icon_swf from './swf.png';
import Icon_systemsmanager from './systemsmanager.png';
import Icon_transform from './transform.png';
import Icon_vpc from './vpc.png';
import Icon_workspaces from './workspaces.png';
import Icon_workspacesweb from './workspacesweb.png';

export const ICONS: Record<string, string> = {
  "a2i": Icon_a2i,
  "aidevops": Icon_aidevops,
  "amazonq": Icon_amazonq,
  "apigateway": Icon_apigateway,
  "appstream2": Icon_appstream2,
  "appstudio": Icon_appstudio,
  "appsync": Icon_appsync,
  "athena": Icon_athena,
  "bedrock": Icon_bedrock,
  "bedrockagentcore": Icon_bedrockagentcore,
  "billing": Icon_billing,
  "biodiscovery": Icon_biodiscovery,
  "cloudformation": Icon_cloudformation,
  "cloudfront": Icon_cloudfront,
  "cloudtrail": Icon_cloudtrail,
  "cloudwatch": Icon_cloudwatch,
  "composer": Icon_composer,
  "config": Icon_config,
  "connecthealth": Icon_connecthealth,
  "console": Icon_console,
  "costexplorer": Icon_costexplorer,
  "costmanagement": Icon_costmanagement,
  "datatransferterminal": Icon_datatransferterminal,
  "deadlinecloud": Icon_deadlinecloud,
  "dynamodb": Icon_dynamodb,
  "ec2": Icon_ec2,
  "ec2globalview": Icon_ec2globalview,
  "ecr": Icon_ecr,
  "ecs": Icon_ecs,
  "eks": Icon_eks,
  "elementalinference": Icon_elementalinference,
  "endusermessaging": Icon_endusermessaging,
  "eventbridge": Icon_eventbridge,
  "evs": Icon_evs,
  "firehose": Icon_firehose,
  "fis": Icon_fis,
  "flink": Icon_flink,
  "forsap": Icon_forsap,
  "gameliftservers": Icon_gameliftservers,
  "gameliftstreams": Icon_gameliftstreams,
  "glacier": Icon_glacier,
  "globalview": Icon_globalview,
  "glue": Icon_glue,
  "grafana": Icon_grafana,
  "iam": Icon_iam,
  "kms": Icon_kms,
  "lambda": Icon_lambda,
  "mediaconnect": Icon_mediaconnect,
  "mediaconvert": Icon_mediaconvert,
  "medialive": Icon_medialive,
  "mediapackage": Icon_mediapackage,
  "mediastore": Icon_mediastore,
  "mediatailor": Icon_mediatailor,
  "memorydb": Icon_memorydb,
  "msk": Icon_msk,
  "mwaa": Icon_mwaa,
  "notifications": Icon_notifications,
  "novaact": Icon_novaact,
  "odb": Icon_odb,
  "opensearch": Icon_opensearch,
  "organizations": Icon_organizations,
  "outposts": Icon_outposts,
  "partnercentral": Icon_partnercentral,
  "pcs": Icon_pcs,
  "prometheus": Icon_prometheus,
  "rbin": Icon_rbin,
  "rds": Icon_rds,
  "resourcegroups": Icon_resourcegroups,
  "route53": Icon_route53,
  "route53globalresolver": Icon_route53globalresolver,
  "route53recovery": Icon_route53recovery,
  "rtbfabric": Icon_rtbfabric,
  "s3": Icon_s3,
  "sagemaker": Icon_sagemaker,
  "scn": Icon_scn,
  "secretsmanager": Icon_secretsmanager,
  "securityagent": Icon_securityagent,
  "securityir": Icon_securityir,
  "servicequotas": Icon_servicequotas,
  "ses": Icon_ses,
  "snowfamily": Icon_snowfamily,
  "sns": Icon_sns,
  "sqs": Icon_sqs,
  "sso": Icon_sso,
  "stepfunctions": Icon_stepfunctions,
  "sustainability": Icon_sustainability,
  "swf": Icon_swf,
  "systemsmanager": Icon_systemsmanager,
  "transform": Icon_transform,
  "vpc": Icon_vpc,
  "workspaces": Icon_workspaces,
  "workspacesweb": Icon_workspacesweb,
};

export type IconId = "a2i" | "aidevops" | "amazonq" | "apigateway" | "appstream2" | "appstudio" | "appsync" | "athena" | "bedrock" | "bedrockagentcore" | "billing" | "biodiscovery" | "cloudformation" | "cloudfront" | "cloudtrail" | "cloudwatch" | "composer" | "config" | "connecthealth" | "console" | "costexplorer" | "costmanagement" | "datatransferterminal" | "deadlinecloud" | "dynamodb" | "ec2" | "ec2globalview" | "ecr" | "ecs" | "eks" | "elementalinference" | "endusermessaging" | "eventbridge" | "evs" | "firehose" | "fis" | "flink" | "forsap" | "gameliftservers" | "gameliftstreams" | "glacier" | "globalview" | "glue" | "grafana" | "iam" | "kms" | "lambda" | "mediaconnect" | "mediaconvert" | "medialive" | "mediapackage" | "mediastore" | "mediatailor" | "memorydb" | "msk" | "mwaa" | "notifications" | "novaact" | "odb" | "opensearch" | "organizations" | "outposts" | "partnercentral" | "pcs" | "prometheus" | "rbin" | "rds" | "resourcegroups" | "route53" | "route53globalresolver" | "route53recovery" | "rtbfabric" | "s3" | "sagemaker" | "scn" | "secretsmanager" | "securityagent" | "securityir" | "servicequotas" | "ses" | "snowfamily" | "sns" | "sqs" | "sso" | "stepfunctions" | "sustainability" | "swf" | "systemsmanager" | "transform" | "vpc" | "workspaces" | "workspacesweb";
