// AUTO-GENERATED by scripts/build-icons.ts. Do not edit.
import Icon_apigateway from './apigateway.png';
import Icon_appsync from './appsync.png';
import Icon_athena from './athena.png';
import Icon_bedrock from './bedrock.png';
import Icon_billing from './billing.png';
import Icon_cloudformation from './cloudformation.png';
import Icon_cloudfront from './cloudfront.png';
import Icon_cloudtrail from './cloudtrail.png';
import Icon_cloudwatch from './cloudwatch.png';
import Icon_config from './config.png';
import Icon_costexplorer from './costexplorer.png';
import Icon_dynamodb from './dynamodb.png';
import Icon_ec2 from './ec2.png';
import Icon_ecr from './ecr.png';
import Icon_ecs from './ecs.png';
import Icon_eks from './eks.png';
import Icon_eventbridge from './eventbridge.png';
import Icon_glue from './glue.png';
import Icon_iam from './iam.png';
import Icon_kms from './kms.png';
import Icon_lambda from './lambda.png';
import Icon_opensearch from './opensearch.png';
import Icon_organizations from './organizations.png';
import Icon_rds from './rds.png';
import Icon_route53 from './route53.png';
import Icon_s3 from './s3.png';
import Icon_sagemaker from './sagemaker.png';
import Icon_secretsmanager from './secretsmanager.png';
import Icon_ses from './ses.png';
import Icon_sns from './sns.png';
import Icon_sqs from './sqs.png';
import Icon_sso from './sso.png';
import Icon_stepfunctions from './stepfunctions.png';
import Icon_systemsmanager from './systemsmanager.png';
import Icon_vpc from './vpc.png';

export const ICONS: Record<string, string> = {
  "apigateway": Icon_apigateway,
  "appsync": Icon_appsync,
  "athena": Icon_athena,
  "bedrock": Icon_bedrock,
  "billing": Icon_billing,
  "cloudformation": Icon_cloudformation,
  "cloudfront": Icon_cloudfront,
  "cloudtrail": Icon_cloudtrail,
  "cloudwatch": Icon_cloudwatch,
  "config": Icon_config,
  "costexplorer": Icon_costexplorer,
  "dynamodb": Icon_dynamodb,
  "ec2": Icon_ec2,
  "ecr": Icon_ecr,
  "ecs": Icon_ecs,
  "eks": Icon_eks,
  "eventbridge": Icon_eventbridge,
  "glue": Icon_glue,
  "iam": Icon_iam,
  "kms": Icon_kms,
  "lambda": Icon_lambda,
  "opensearch": Icon_opensearch,
  "organizations": Icon_organizations,
  "rds": Icon_rds,
  "route53": Icon_route53,
  "s3": Icon_s3,
  "sagemaker": Icon_sagemaker,
  "secretsmanager": Icon_secretsmanager,
  "ses": Icon_ses,
  "sns": Icon_sns,
  "sqs": Icon_sqs,
  "sso": Icon_sso,
  "stepfunctions": Icon_stepfunctions,
  "systemsmanager": Icon_systemsmanager,
  "vpc": Icon_vpc,
};

export type IconId = "apigateway" | "appsync" | "athena" | "bedrock" | "billing" | "cloudformation" | "cloudfront" | "cloudtrail" | "cloudwatch" | "config" | "costexplorer" | "dynamodb" | "ec2" | "ecr" | "ecs" | "eks" | "eventbridge" | "glue" | "iam" | "kms" | "lambda" | "opensearch" | "organizations" | "rds" | "route53" | "s3" | "sagemaker" | "secretsmanager" | "ses" | "sns" | "sqs" | "sso" | "stepfunctions" | "systemsmanager" | "vpc";
