#!/usr/bin/env tsx
// Pre-build pipeline: vendor icons → optimized icons in src/assets/icons/.
// Reads scripts/icon-map.json (id → filename), validates against
// catalog/services.json, walks vendor/aws-icons-source/ recursively to
// resolve filenames at any depth, writes per-id files + index.ts.
//
// Source files may be .svg (optimized via svgo) or .png/.jpg/.webp (copied
// raw). Output extension matches source extension.
//
// Flags:
//   --check           exit non-zero if outputs are stale (CI guardrail)
//   --allow-missing   warn instead of fail when source SVGs are absent
//   --source <dir>    override vendor/aws-icons-source/

import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { optimize } from 'svgo';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const args = new Set(process.argv.slice(2));
const CHECK = args.has('--check');
const ALLOW_MISSING = args.has('--allow-missing');

const SOURCE_DIR = resolveFlag('--source') ?? process.env.ICONS_SOURCE_DIR ?? join(ROOT, 'vendor/aws-icons-source');
const OUT_DIR = join(ROOT, 'src/assets/icons');
const SERVICES_PATH = join(ROOT, 'catalog/services.json');
const MAP_PATH = join(ROOT, 'scripts/icon-map.json');
const LOCK_PATH = join(ROOT, '.cache/icons.lock');

type IconMap = Record<string, string>;
type Service = { id: string };
type Catalog = { schemaVersion: number; version: string; services: Service[] };

function resolveFlag(name: string): string | undefined {
  const idx = process.argv.indexOf(name);
  return idx >= 0 ? process.argv[idx + 1] : undefined;
}

function readJson<T>(p: string): T {
  return JSON.parse(readFileSync(p, 'utf8')) as T;
}

const ICON_EXTS = new Set(['.svg', '.png', '.jpg', '.jpeg', '.webp']);

function extOf(name: string): string {
  const i = name.lastIndexOf('.');
  return i >= 0 ? name.slice(i).toLowerCase() : '';
}

function walkIcons(dir: string): Map<string, string> {
  const out = new Map<string, string>();
  if (!existsSync(dir)) return out;
  const stack: string[] = [dir];
  while (stack.length) {
    const cur = stack.pop()!;
    for (const entry of readdirSync(cur, { withFileTypes: true })) {
      const full = join(cur, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.isFile() && ICON_EXTS.has(extOf(entry.name))) {
        // First match wins. Multiple matches → ambiguous, log warning.
        if (out.has(entry.name)) {
          console.warn(`[icons] duplicate filename "${entry.name}" — keeping first: ${relative(ROOT, out.get(entry.name)!)}`);
          continue;
        }
        out.set(entry.name, full);
      }
    }
  }
  return out;
}

function hashInputs(map: IconMap, sourceFiles: Map<string, string>): string {
  const h = createHash('sha256');
  h.update(JSON.stringify(map));
  for (const [name, full] of [...sourceFiles].sort()) {
    if (!Object.values(map).includes(name)) continue;
    h.update(name);
    h.update(String(statSync(full).mtimeMs));
    h.update(String(statSync(full).size));
  }
  return h.digest('hex');
}

function optimizeSvg(raw: string, name: string): string {
  const result = optimize(raw, {
    multipass: true,
    plugins: [
      {
        name: 'preset-default',
        params: {
          overrides: {
            removeViewBox: false,
            cleanupIds: { minify: true },
          },
        },
      },
      'removeDimensions',
    ],
  });
  if ('error' in result && result.error) {
    throw new Error(`svgo failed for ${name}: ${result.error}`);
  }
  return result.data;
}

function writeIfChanged(p: string, content: string): boolean {
  if (existsSync(p) && readFileSync(p, 'utf8') === content) return false;
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
  return true;
}

function emitIndex(entries: { id: string; ext: string }[]): string {
  const imports = entries.map(({ id, ext }) => `import ${idVar(id)} from './${id}${ext}';`).join('\n');
  const map = entries.map(({ id }) => `  ${JSON.stringify(id)}: ${idVar(id)},`).join('\n');
  return `// AUTO-GENERATED by scripts/build-icons.ts. Do not edit.
${imports}

export const ICONS: Record<string, string> = {
${map}
};

export type IconId = ${entries.length ? entries.map(({ id }) => JSON.stringify(id)).join(' | ') : 'never'};
`;
}

function idVar(id: string): string {
  return `Icon_${id.replace(/[^a-zA-Z0-9]/g, '_')}`;
}

function main(): void {
  const catalog = readJson<Catalog>(SERVICES_PATH);
  const services = catalog.services;
  const map = readJson<IconMap>(MAP_PATH);
  // Strip the $schema doc field if present.
  delete (map as Record<string, string>)['$schema'];

  const serviceIds = new Set(services.map((s) => s.id));
  const mapIds = new Set(Object.keys(map));

  // Validate map symmetry.
  const unknownInMap = [...mapIds].filter((id) => !serviceIds.has(id));
  if (unknownInMap.length) {
    console.warn(`[icons] icon-map has entries with no matching service: ${unknownInMap.join(', ')}`);
  }

  const sourceFiles = walkIcons(SOURCE_DIR);
  const inputHash = hashInputs(map, sourceFiles);
  const lock = existsSync(LOCK_PATH) ? readFileSync(LOCK_PATH, 'utf8').trim() : '';

  if (CHECK) {
    if (lock !== inputHash) {
      console.error('[icons] stale: run `npm run icons:build` and commit changes.');
      process.exit(1);
    }
    console.log('[icons] up to date.');
    return;
  }

  if (lock === inputHash && existsSync(join(OUT_DIR, 'index.ts'))) {
    console.log('[icons] cached (no changes).');
    return;
  }

  const missing: string[] = [];
  const generated: { id: string; ext: string }[] = [];

  // Clear stale outputs (any icon ext + index.ts).
  if (existsSync(OUT_DIR)) {
    for (const entry of readdirSync(OUT_DIR)) {
      if (ICON_EXTS.has(extOf(entry)) || entry === 'index.ts') {
        rmSync(join(OUT_DIR, entry));
      }
    }
  }
  mkdirSync(OUT_DIR, { recursive: true });

  for (const id of [...serviceIds].sort()) {
    const filename = map[id];
    if (!filename) {
      missing.push(`${id} (no mapping)`);
      continue;
    }
    const sourcePath = sourceFiles.get(filename);
    if (!sourcePath) {
      missing.push(`${id} → ${filename} (not found in ${relative(ROOT, SOURCE_DIR)})`);
      continue;
    }
    const ext = extOf(filename);
    const outPath = join(OUT_DIR, `${id}${ext}`);
    if (ext === '.svg') {
      const raw = readFileSync(sourcePath, 'utf8');
      const optimized = optimizeSvg(raw, filename);
      writeIfChanged(outPath, optimized);
    } else {
      copyFileSync(sourcePath, outPath);
    }
    generated.push({ id, ext });
  }

  writeIfChanged(join(OUT_DIR, 'index.ts'), emitIndex(generated));

  mkdirSync(dirname(LOCK_PATH), { recursive: true });
  writeFileSync(LOCK_PATH, inputHash);

  console.log(`[icons] wrote ${generated.length} icons → ${relative(ROOT, OUT_DIR)}/`);
  if (missing.length) {
    const msg = `[icons] missing for ${missing.length} services:\n  - ${missing.join('\n  - ')}`;
    if (ALLOW_MISSING || !sourceFiles.size) {
      console.warn(msg);
      if (!sourceFiles.size) {
        console.warn(`[icons] hint: drop AWS Architecture Icons (.svg/.png) into ${relative(ROOT, SOURCE_DIR)}/ (any nested layout).`);
      }
    } else {
      console.error(msg);
      process.exit(1);
    }
  }
}

main();
